/**
 ******************************************************************************
 * @file    customAPIcallback_sim.c
 * @author  SIANA Systems
 * @date    02/2021
 * @brief   Implements customAPIcallback API on simulator code
 *
 ******************************************************************************
 * @attention
 *
 * <h2><center>© COPYRIGHT 2021 SIANA Systems</center></h2>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 ******************************************************************************
 */
 
/** @addtogroup SIANA
 * @{
 */
/** @addtogroup Controllers
 * @{
 */
/** @addtogroup customAPIcallback_sim
 * @{
 */
/**
 * @defgroup PUBLIC_Definitions          PUBLIC constants
 * @defgroup PUBLIC_Macros               PUBLIC macros
 * @defgroup PUBLIC_Types                PUBLIC data-types
 * @defgroup PUBLIC_API                  PUBLIC API
 * @defgroup PRIVATE_TUNABLES            Private compile-time tunables
 * @defgroup PRIVATE_Definitions         Private constants
 * @defgroup PRIVATE_Macros              Private macros
 * @defgroup PRIVATE_Types               Private data-types
 * @defgroup PRIVATE_Data                Private data / variables
 * @defgroup PRIVATE_Functions           Private functions
 */
 
#ifdef SIMULATOR
 
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <gui/simulator/customAPIcallback.h>
#include <gui/simulator/decodeDataHandler.h>

/*----------------------------------------------------------------------------*/
/** @addtogroup PRIVATE_TUNABLES                                              */
/**@{                                                                         */
/*----------------------------------------------------------------------------*/


/** @} */
/*----------------------------------------------------------------------------*/
/** @addtogroup PRIVATE_Definitions                                           */
/**@{                                                                         */
/*----------------------------------------------------------------------------*/

/* Maximum size of dummy barcodes */
#define MAX_DUMMY_BARCODE_SIZE                0x40  /* 64 characters */
#define MIN_DUMMY_BARCODE_SIZE                0x08  /*  8 characters */

/** @} */
/*----------------------------------------------------------------------------*/
/** @addtogroup PRIVATE_Macros                                                */
/**@{                                                                         */
/*----------------------------------------------------------------------------*/
 
/** @} */
/*----------------------------------------------------------------------------*/
/** @addtogroup PRIVATE_Types                                                 */
/**@{                                                                         */
/*----------------------------------------------------------------------------*/

/** @} */
/*----------------------------------------------------------------------------*/
/** @addtogroup PRIVATE_Functions                                             */
/**@{                                                                         */
/*----------------------------------------------------------------------------*/

/** @} */
/*----------------------------------------------------------------------------*/
/** @addtogroup PRIVATE_Data                                                  */
/**@{                                                                         */
/*----------------------------------------------------------------------------*/

/* buffer that will hold dummy application data */

static char dummy_data[MAX_DUMMY_BARCODE_SIZE+1] = {0};
static uint16_t dummy_status = 0;

/* internal flag to know if a new dummy data has been generated by simulator */

static bool new_scan = false;
static bool new_status = false;

/* count seed for Random/dummy function */
static uint32_t count = 0;

/** @} */
/*----------------------------------------------------------------------------*/
/** @addtogroup PUBLIC_API                                                    */
/**@{                                                                         */
/*----------------------------------------------------------------------------*/

/**
 * API: CST_APIcbSendDataToGUI()
 */
int8_t CST_APIcbSendDataToGUI(BarcodeRecord_t *const dest)
{
  uint8_t dummy_len;
  int i = 0;
  /* Generate new dummy data - seed new value */
  srand(count);
  count++;
  // modified for test purposes
  if ((count == 2) || (count == 6) || (count == 10))
  {
	  new_scan = true;
	  return true;
  }
  
  /* generate dummy length */
  dummy_len = (rand() & 0x000000FF) >> 2;
  if (dummy_len < MIN_DUMMY_BARCODE_SIZE)
  {
	dummy_len = MIN_DUMMY_BARCODE_SIZE;
  }
  
  for(i = 0; i < dummy_len; i++)
  {
	  dummy_data[i] = (uint8_t)('0' + (rand() % 10));
  }
  dummy_data[i] = 0; /* Terminate random string of numbers*/
  
  /* update internal flag to let know the poling function we have updated data */
  new_scan = true;
  
  return true;
}

/**
 * API: CST_APIcbGetDecodeData()
 */
char *CST_APIcbGetDecodeData(char **getMsg)
{
  /* If we have generated new dummy data */
  if(new_scan)
  {
	/* Link it */
	*getMsg = dummy_data;
	new_scan = false;
    return *getMsg;
  }
  
  return NULL;
}

/**
 * API: CST_APIcbSendKeyToGUI()
 */
int8_t CST_APIcbSendKeyToGUI(uint8_t *key) 
{
  return 0;
}

/**
 * API: CST_APIcbRxKeyData()
 */
int8_t CST_APIcbRxKeyData(uint8_t *getKey) 
{
  return 0;
}

/**
 * API: CST_APIcbSendBTBatStatus()
 */
int8_t CST_APIcbGetBackendStatus(uint16_t *status) 
{
  /* If a new dummy status has been generated, send it to UI */
  if (new_status)
  {
    *status = dummy_status;
    new_status = false;
    return true;
  }
  return false;
}

/**
 * API: CST_APIcbSendBTBatStatus()
 */
int8_t CST_APIcbSendBackendStatus(uint16_t *status)
{
  /* Store a new dummy status for UI to retrieve */
  dummy_status = *status;
  new_status = true;
  return true;
}

uint32_t CST_APIGetCanopyTicks()
{
	return 0;
}

#endif
